#!/bin/bash
#
DEBUG=1
EZSCAN=`which ezscan`
siteaccess_list=`$EZSCAN -s`
RETVAL=$?
if [ $RETVAL -ne 0 ] ; then
  echo $siteaccess_list
  exit 1
fi
VARDIR=`$EZSCAN  -B FileSettings -V VarDir`
[ $DEBUG -eq 1 ] && echo "VARDIR=$VARDIR"

expiri=$VARDIR/cache/expiry.php
if [ -f "$expiri" ] ; then  
   ls -la "$expiri"
fi

[ $DEBUG -eq 1 ] && echo "siteaccess_list=$siteaccess_list"
for siteaccess in $siteaccess_list ; do
	VARDIR=`$EZSCAN -S $siteaccess  -B FileSettings -V VarDir`
	[ $DEBUG -eq 1 ] && echo "siteaccess=$siteaccess VARDIR=$VARDIR"
    CacheDir=`$EZSCAN -S $siteaccess  -B FileSettings -V CacheDir`
    [ -z "$CacheDir" ] && CacheDir=$VARDIR/cache/content/$siteaccess/
    if [ -d "$CacheDir" ] ; then
		du -sh "$CacheDir"
		expiri=$VARDIR/cache/expiry.php
        if [ -f "$expiri" ] ; then 
           ls -la "$expiri"
        fi
    fi
done