#!/bin/bash
#
# ezscan script
# v. 0.0.2
#
# getting info from ezpublish installations
#
#
#* Return values:
# 0: OK
# 1: error
#
###################################################################
# 
#
# v.0.2
# introdotto script bash
#
##################################################################
#
#
VERBOSE=0
#
# getops see /usr/share/doc/util-linux/examples/getopt-parse.bash
this_script=`basename $0`
#TEMP=`getopt -o vhd:B:V:c:: --long verbose,help,directory:,ini-block-name:,ini-var-name:,c-long:: \
#     -n "$this_script" -- "$@"`
TEMP=`getopt -o vhB:V:c:: --long verbose,help,ini-block-name:,ini-var-name:,c-long:: \
     -n "$this_script" -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"
while true ; do
    case "$1" in
        -v|--verbose) echo "Found the -v (verbose) option"
				VERBOSE=1 
				shift ;;
        -h|--help) 
				if [ $VERBOSE -eq 1 ]
				       then
				         echo "Found the -h (help) option"
				fi
				echo "usage: ezscan [-v|--verbose] [-d|directory]"
				echo "              [-B|--ini-block-name block-name] [-V|--ini-var-name var-name]"
                echo "              [-B|--ini-block-name block-name] [-V|--ini-var-name var-name]"
                echo "              [-h|--help]"
				echo "              DIRECTORY"
				echo "e.g."
				echo "ezscan  /home/httpd/mysite.site.com/html"
				echo "ezscan -B DatabaseSettings -V User     # default to current dir"
				echo "ezscan -h"
				echo 
				exit;;
    #    -d|--directory) 
	#		EZ_DIR="$2" 
    #        if [ $VERBOSE -eq 1 ]; then 
    #          echo "Found the -d (documentroot) option, with value: $2"
    #        fi 
    #     	 shift 2 ;;
        -B|--ini-block-name)
            EZINI_BLOCK_NAME="$2"
            if [ $VERBOSE -eq 1 ]; then
              echo "Found the -B (--ini-block-name) option, with value: $2"
            fi
            shift 2 ;;
        -V|--ini-var-name)
            EZINI_VAR_NAME="$2"
            if [ $VERBOSE -eq 1 ]; then
              echo "Found the -V (--ini-var-name) option, with value: $2"
            fi
            shift 2 ;;
        -c|--c-long)
            # c has an optional argument. As we are in quoted mode,
            # an empty parameter will be generated if its optional
            # argument is not found.
            case "$2" in
                "") echo "Option c, no argument"; shift 2 ;;
                *)  echo "Option c, argument \`$2'" ; shift 2 ;;
            esac ;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
    esac
done



if [ $VERBOSE -eq 1 ] ; then
	echo "Remaining arguments:"
	for arg do echo '--> '"\`$arg'" ; done
fi

count=0
for arg do
  argomento="$arg"
  count=$[ $count + 1 ]    
done

# if no argument set argument to current dir
if [ $count -eq 0 ] ; then
  EZ_DIR=`pwd`
  if [ $VERBOSE -eq 1 ] ; then
    echo "No argument found: set EZ_DIR to current dir: $EZ_DIR"
  fi
fi

if [ $count -eq 1 ] ; then
  if [ $VERBOSE -eq 1 ] ; then
    echo "One argument found: set EZ_DIR to current dir: $argomento"
  fi
  EZ_DIR=$argomento
fi

if [ $count -ge 2 ] ; then
  echo "Too many arguments: only zero or 1 argument can be entered"
  EXIT_FOR_ERROR=yes
  
fi

#if [ -z  $arg ] ; then
#	echo "try `basename $0` -h"
#	exit 
#fi

#
#echo "Unknown option: $1"
#echo "Try 'ezscan -h' for more information."

# Test presence of mandatory options
#if [ -z "$EZ_DIR" ]
#then
#  echo "missing  -d (documentroot) option"
#  EXIT_FOR_ERROR=yes
#fi

if ( [ "$EZINI_BLOCK_NAME" ] && [ -z "$EZINI_VAR_NAME" ] ) || ( [ -z "$EZINI_BLOCK_NAME" ] && [  "$EZINI_VAR_NAME" ] )
then
  echo "eZIni output needs both blockName & varName"
  EXIT_FOR_ERROR=yes
fi


if [ $EXIT_FOR_ERROR ]
then
  #echo "ERROR"
  echo "Try 'ezscan -h'"
  exit 1
fi

#
#
# set defaults

if [ -z "$EZ_DIR" ]
then
    EZ_DIR=`pwd`
fi



if [ $VERBOSE -eq 1 ]
then
  echo "# Executing..."
fi


EZPCOMP_EZ_DIR=''
cd $EZ_DIR

# chech if we are inside an eZ Publish directory
#    populate $EZPCOMP_IS_EZ_DIR, $EZPCOMP_EZ_DIR
#
    if [ -n "$EZPCOMP_IS_EZ_DIR" ]; then EZPCOMP_IS_EZ_DIR=0; fi
    # Exit directly if not in an ezpublish instance
    CWD=$(pwd)
    EZPCOMP_PWD=$CWD

    # Reset the previous working directory if it doesn't match the current one
    if [ -n "$EZPCOMP_PWD" ] || [ "$EZPCOMP_PWD" -ne "$CWD" ]; then
        #local cwd_array ifs_bak
        IFS_BAK=$IFS
        IFS="/"
    CWD_ARRAY=( $CWD )
        EZPCOMP_IS_EZ_DIR=0
    for(( index=${#CWD_ARRAY[*]} ; index > 0 ; index-- ))
        do
            testdir="${CWD_ARRAY[*]:0:$index}"
            #_ezp_p_debug "$index: $testdir/lib/version.php"
            if [ -f "$testdir/lib/version.php" ]; then
                #_ezp_p_debug "$testdir did match"
                EZPCOMP_EZ_DIR="$testdir"
                EZPCOMP_IS_EZ_DIR=1
                EZPCOMP_PWD=$CWD
                export EZPCOMP_EZ_DIR
                export EZPCOMP_IS_EZ_DIR
                break
            fi
        done
        IFS=$IFS_BAK
    fi

if [ $VERBOSE -eq 1 ]
then
  echo '$EZPCOMP_EZ_DIR='$EZPCOMP_EZ_DIR
  echo '$EZPCOMP_IS_EZ_DIR='$EZPCOMP_IS_EZ_DIR
fi


# Not an eZ Dir
if [ -z "$EZPCOMP_IS_EZ_DIR" ] || [ "$EZPCOMP_IS_EZ_DIR" -eq 0 ]; then
  echo "You are not in a eZ Publish directory, or the documentroot you supplied is not an eZ Publish directory"
  exit 1
fi


if [ $VERBOSE -eq 1 ] ; then
  echo  "# Executing: "
  echo  "cd $EZPCOMP_EZ_DIR"
fi
cd $EZPCOMP_EZ_DIR


PHP_EZSCAN=`which php_ezscan`

#/home/developer/scripts/ezscan_dev/ezscan-php.php $EZINI_BLOCK_NAME $EZINI_VAR_NAME
if  [ "$EZINI_BLOCK_NAME" ] && [ "$EZINI_VAR_NAME" ] ; then
  if [ $VERBOSE -eq 1 ] ; then 
    echo  "# Executing: "
    echo "$PHP_EZSCAN _ini $EZINI_BLOCK_NAME $EZINI_VAR_NAME" 
  fi
  $PHP_EZSCAN  _ini $EZINI_BLOCK_NAME $EZINI_VAR_NAME
fi