#!/bin/bash
#
DEBUG=1
EZSCAN=`which ezscan`

output=`$EZSCAN -s`
RETVAL=$?
if [ $RETVAL -ne 0 ] ; then
  echo $output
  exit 1
fi
siteaccess_list=$output

# conta numero totale dei file di una directory che siano + vecchi di timestamp
# parametri: directory, timestamp
function files_number {
  local aux_filename="/tmp/_files_number.tmp"
  local my_dir=$1
  local my_timestamp=$2
  local timestamp_in_words=`date -d @$my_timestamp`
  touch -d "$timestamp_in_words" $aux_filename
  if [ -d "$my_dir" ] ; then
    find $my_dir -not -newer $aux_filename | wc -l
  fi

}
# calcola dimensione totale dei file di una directory che siano + vecchi di timestamp
# parametri: directory, timestamp
function total_files_size {
  local aux_filename="/tmp/_total_files_size.tmp"
  local my_dir=$1
  local my_timestamp=$2
  local timestamp_in_words=`date -d @$my_timestamp`
  touch -d "$timestamp_in_words" $aux_filename
  if [ -d "$my_dir" ] ; then
    find $my_dir -not -newer $aux_filename | xargs  stat --format=%s | awk '{s+=$1} END {print s}'
    #return `find $my_dir -not -newer  $aux_filename | xargs stat --format=%s | paste -sd+ - | bc`
  fi
}




# we move to main ezpublish dir
cd `$EZSCAN -d`


[ $DEBUG -eq 1 ] && echo && echo "###########   Ez template-block-cache ############" 

VarDir=`$EZSCAN  -B FileSettings -V VarDir`


[ $DEBUG -eq 1 ] && echo "VarDir=$VarDir"



expiri=$VarDir/cache/expiry.php
if [ -f "$expiri" ] ; then
   echo "global expiry found:" `ls -la "$expiri"`
   expiri_timestamp=`cat $expiri | grep "'template-block-cache'" | sed "s/'template-block-cache' => //" | sed 's/ //g' | sed 's/,//'`
   echo "  with 'template-block-cache' timestamp=$expiri_timestamp : " `date -d @$expiri_timestamp` 
   echo
fi

CacheDir=$VarDir/cache/template-block
expiri_timestamp_meno_1m=$(($expiri_timestamp-60))
if [ -d "$CacheDir" ] ; then
  echo "found template-block dir: $CacheDir"
  echo 
  echo " TOTAL size:          " `du -sh "$CacheDir"`
  num_total=`files_number $CacheDir $expiri_timestamp_meno_1m`
  size_total=`total_files_size $CacheDir $expiri_timestamp_meno_1m`
  echo 
  echo " Files older than expiry timestamp (unnecessary files):"
  echo "     Total number: $num_total"
  site_total_in_megabytes=`echo "$size_total/(1024*1024)" | bc`
  echo "     Total size (bytes): $size_total bytes ($site_total_in_megabytes MB)"
else
  echo "    could not find template-block dir: $CacheDir"
fi
echo
